# Generated by Django 5.0.3 on 2024-03-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
