# Generated by Django 5.0.3 on 2024-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('register_limit_date', models.DateField(blank=True, null=True)),
                ('selection_start_date', models.DateField(blank=True, null=True)),
                ('selection_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
                'db_table': 'seleccion',
            },
        ),
    ]
