# Generated by Django 5.0.3 on 2024-04-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estado de selección',
                'verbose_name_plural': 'Estados del proceso de selección',
                'db_table': 'selection_state',
            },
        ),
        migrations.AlterField(
            model_name='selection',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.selectionstate'),
        ),
    ]
