# Generated by Django 5.0.3 on 2024-04-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_selectionstate_alter_selection_current_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selectionstate',
            table='estado_seleccion',
        ),
    ]
