# Generated by Django 5.0.3 on 2024-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_alter_selectionstate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
