# Generated by Django 5.0.3 on 2024-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_selection_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='register_limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='selection_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='selection_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
