# Generated by Django 5.0.3 on 2024-04-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0009_rename_direction_becatrabajo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becatrabajo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='becatrabajo',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='horarios/'),
        ),
    ]
