# Generated by Django 5.0.3 on 2024-04-12 12:37

import selection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0010_alter_becatrabajo_photo_alter_becatrabajo_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='becatrabajo',
            name='extra_studies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='becatrabajo',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='becatrabajo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=selection.models.BecaTrabajo.photo_path),
        ),
        migrations.AlterField(
            model_name='becatrabajo',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to=selection.models.BecaTrabajo.schedule_path),
        ),
    ]
