# Generated by Django 5.0.3 on 2024-04-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0011_becatrabajo_extra_studies_becatrabajo_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becatrabajo',
            name='sended_form',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
