# Generated by Django 5.0.3 on 2024-04-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0012_becatrabajo_sended_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Estado actual del beca',
                'db_table': 'estado_beca',
            },
        ),
        migrations.AddField(
            model_name='becatrabajo',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.becastate'),
        ),
    ]
