# Generated by Django 5.0.3 on 2024-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0013_becastate_becatrabajo_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='total_becas',
            field=models.IntegerField(blank=True, default=16, max_length=40, null=True),
        ),
    ]
