# Generated by Django 5.0.3 on 2024-04-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0014_selection_total_becas'),
        ('ubications', '0003_ubication_description_ubication_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='becatrabajo',
            name='ubication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubications.ubication'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='total_becas',
            field=models.IntegerField(blank=True, default=16, null=True),
        ),
    ]
