# Generated by Django 5.0.3 on 2024-06-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_becatrabajo_ubication_alter_selection_total_becas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('beca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.becatrabajo')),
            ],
            options={
                'verbose_name': 'Horario de beca',
                'verbose_name_plural': 'Horarios de becas',
                'db_table': 'horario_becas',
            },
        ),
    ]
