# Generated by Django 5.0.3 on 2024-06-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0016_becaschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becaschedule',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beca_schedules', to='selection.becatrabajo'),
        ),
    ]
