# Generated by Django 5.0.3 on 2024-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='documents')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
