# Generated by Django 5.0.3 on 2024-12-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('codigo', models.CharField(help_text='Código de la beca', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la beca', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la beca', null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la beca', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la beca', verbose_name='Fecha de fin')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la beca', max_digits=10, verbose_name='Monto')),
            ],
        ),
    ]
