# Generated by Django 5.0.3 on 2024-12-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del periodo de selección', max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del periodo', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del periodo', verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True, help_text='Indica si es el periodo de selección actual', verbose_name='Activo')),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='estado',
            field=models.BooleanField(default=True, help_text='Estado de la beca (activa/inactiva)', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='beca',
            name='selection',
            field=models.ForeignKey(help_text='Selección a la que pertenece la beca', null=True, on_delete=django.db.models.deletion.CASCADE, to='beca.selection', verbose_name='Selección'),
        ),
    ]
