# Generated by Django 5.0.3 on 2024-12-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beca', '0002_selection_beca_estado_beca_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='selection',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la selección está activa', verbose_name='Activo'),
        ),
    ]
