# Generated by Django 5.0.3 on 2024-04-22 17:10

import ubications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0002_alter_ubication_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ubication',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=ubications.models.Ubication.photo_path),
        ),
    ]
