# Generated by Django 5.0.3 on 2024-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0003_ubication_description_ubication_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubication',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='ubication',
            name='is_schedule_office',
        ),
        migrations.DeleteModel(
            name='HourSchedule',
        ),
    ]
