# Generated by Django 5.0.3 on 2024-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0004_remove_ubication_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='schedule',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
