# Generated by Django 5.0.3 on 2024-05-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_becatrabajo_ubication_alter_selection_total_becas'),
        ('ubications', '0005_ubication_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_de_horarios',
            },
        ),
        migrations.RemoveField(
            model_name='ubication',
            name='schedule',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.CharField(max_length=10)),
                ('end_hour', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=60)),
                ('total_becas', models.IntegerField(default=1)),
                ('becas_json', models.JSONField(blank=True, null=True)),
                ('ubication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='ubications.ubication')),
            ],
            options={
                'db_table': 'horarios_por_ubicacion',
                'unique_together': {('ubication', 'start_hour', 'end_hour')},
            },
        ),
        migrations.AddField(
            model_name='ubication',
            name='schedule_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubications.scheduletype'),
        ),
        migrations.CreateModel(
            name='AssignationBecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignations', to='selection.becatrabajo')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignations', to='ubications.schedule')),
            ],
            options={
                'db_table': 'asignaciones_de_becas',
                'unique_together': {('beca', 'schedule')},
            },
        ),
    ]
