# Generated by Django 5.0.3 on 2024-05-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0006_scheduletype_remove_ubication_schedule_schedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('ubication', 'start_hour', 'end_hour', 'days')},
        ),
    ]
