# Generated by Django 5.0.3 on 2024-05-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0007_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField()),
                ('ubication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_format', to='ubications.ubication')),
            ],
            options={
                'db_table': 'formato_de_horarios',
            },
        ),
    ]
