# Generated by Django 5.0.3 on 2024-05-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0009_alter_scheduleformat_ubication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubication',
            name='schedule_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubications.scheduletype'),
        ),
    ]
