# Generated by Django 5.0.3 on 2024-06-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0011_assignationbecas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignationbecas',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignationbecas',
            name='percentage',
            field=models.FloatField(default=60),
        ),
    ]
